config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :user_stocks, only: %i[create destroy]

  resources :friendships, only: %i[create destroy]
  devise_for :users
  root 'welcome#index'

  get 'my_portfolio', to: 'users#my_portfolio'

  get 'my_friends', to: 'users#my_friends'

  get 'search_stock', to: 'stocks#search'

  get 'search_friend', to: 'users#search'
  resources :users, only: [:show]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friendship.rb
# frozen_string_literal: true

class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
# frozen_string_literal: true

class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks
  validates :name, :ticker, presence: true
  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(publishable_token: Rails.application.credentials.iex_client[:iex_api_key],
                                  secret_token: Rails.application.credentials.iex_client[:iex_secret_key],
                                  endpoint: 'https://cloud.iexapis.com/v1')

    begin
      new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name,
          last_price: client.price(ticker_symbol))
    rescue StandardError
      nil
    end
  end

  def self.check_db(ticker_symbol)
    where(ticker: ticker_symbol).first
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def under_stock_limit?
    stocks.count < 10
  end

  def stock_already_tracked?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol)
    return false unless stock

    stocks.where(id: stock.id).exists?
  end

  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name

    'Anonymous'
  end

  def self.search(param)
    param.strip!
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back

    to_send_back
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def self.matches(field_name, param)
    where("#{field_name} like ?", "%#{param}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id == id }
  end

  def not_friends_with?(id_of_friend)
    !friends.where(id: id_of_friend).exists?
  end
end

app/models/user_stock.rb
# frozen_string_literal: true

class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])
  end
end

app/controllers/friendships_controller.rb
# frozen_string_literal: true

class FriendshipsController < ApplicationController
  def create
    friend = User.find(params[:friend])
    current_user.friendships.build(friend_id: friend.id)
    if current_user.save
      flash[:notice] = 'Following friend'
    else
      flash[:alert] = 'There was something wrong with the request'
    end
    redirect_to my_friends_path
  end

  def destroy
    friendship = current_user.friendships.where(friend_id: params[:id]).first
    friendship.destroy
    flash[:notice] = 'Stopped Following'
    redirect_to my_friends_path
  end
end

app/controllers/stocks_controller.rb
# frozen_string_literal: true

class StocksController < ApplicationController
  def search
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock].upcase)
      if @stock
        respond_to do |format|
          format.js { render partial: 'users/result' }
        end

      else
        respond_to do |format|
          flash.now[:alert] = 'Please enter a valid symbol to search'
          format.js { render partial: 'users/result' }
        end

      end
    else
      respond_to do |format|
        flash.now[:alert] = 'Please enter a symbol to search'
        format.js { render partial: 'users/result' }
      end
    end
  end
end

app/controllers/user_stocks_controller.rb
# frozen_string_literal: true

class UserStocksController < ApplicationController
  def create
    stock = Stock.check_db(params[:ticker])
    if stock.blank?

      stock = Stock.new_lookup(params[:ticker])
      stock.save
    end
    @user_stock = UserStock.create(user: current_user, stock:)
    flash[:notice] = "Stock #{stock.name} was  succcessfully added to your portfolio"
    redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
    user_stock.destroy
    flash[:notice] = "#{stock.ticker} was successfully removed from portfolio"
    redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def my_portfolio
    @user = current_user
    @tracked_stocks = current_user.stocks
  end

  def my_friends
    @friends = current_user.friends
  end

  def search
    if params[:friend].present?
      @friends = User.search(params[:friend])
      @friends = current_user.except_current_user(@friends)
      if @friends
        respond_to do |format|
          format.js { render partial: 'users/friend_result' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Couldn't find user"
          format.js { render partial: 'user/friend_result' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = 'Please enter a friend name or email to search'
        format.js { render partial: 'users/friend_result' }
      end
    end
  end

  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  protect_from_forgery except: :portfolio
  def index; end

  def portfolio
    @stock = Stock.new(name: params[:stock])
    return unless @stock

    respond_to do |format|
      format.js { render layout: false }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
# frozen_string_literal: true

module FriendshipsHelper
end

app/helpers/user_stocks_helper.rb
# frozen_string_literal: true

module UserStocksHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/friends/_list.html.erb
    <div class = "friend_table row">
        <div class = "col-9">
            <table class="table table-dark table-borderless table-hover">
                <thead>
                    <tr>
                    <th scope="col">Email</th>
                    <th scope="col">First Name</th>
                    <th scope="col">Last Name</th>
                    <th scope="col">Actions</th>
                    </tr>
                </thead>

                    <% @friends.each do |friend| %>
                        <tbody>
                            <tr>
                            <th scope="row"><%= friend.email %></th>
                            <td><%= friend.first_name %></td>
                            <td><%= friend.last_name %></td>
                            <td><%= link_to "View Profile", user_path(friend), class: "btn btn-xs btn-success" %>
                            <%= button_to  "Stop following", friendship_path(friend), method: :delete,data: {"turbo_confirm": "Are you sure"},class: "btn btn-sm btn-warning" %></td>
                            </tr>
                        </tbody>
                    <% end %>

            </table>

        </div>
    </div>

app/views/layouts/_messages.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show col-sm-9" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show col-sm-9" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
     <%= link_to 'FinanceTracker', root_path, class: 'navbar-brand' %>
     <% if current_user %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item ">
              <% link_style = (request.path == my_portfolio_path) ? 'nav-link active' : "nav-link" %>

              <%= link_to "My Portfolio",my_portfolio_path, class: link_style %>
            </li>
            <li class="nav-item">
            <% friend_link_style = (request.path == my_friends_path) ? 'nav-link active' : "nav-link" %>
             <%= link_to "My Friends",my_friends_path, class: friend_link_style %>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Profile
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to  edit_user_registration_path,class: 'dropdown-item' do %>
                      <%= fa_icon 'edit' %> Edit profile
                    <% end %>
                </li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>

          </ul>
          <ul class= " navbar-nav ml-auto mb-2 mb-lg-0">
            <li class= "nav-item user-name">
              <%= fa_icon 'user' %> <%= current_user.full_name %>
            </li>
            <li class = "nav-item">
              <%= button_to 'Sign out', destroy_user_session_path, method: :delete,class: "btn btn-xs btn-danger logout-btn" %>
            </li>
          </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fixfinance</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <div class = "container">
         <%= render 'layouts/messages' %>
        <%= yield %>
    </div>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

</html>

app/views/stocks/_list.html.erb
    <div class = "row">
        <div class = "col-9">
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                    <th scope="col">Ticker</th>
                    <th scope="col">Name</th>
                    <th scope="col">Price</th>
                    <th scope="col">Actions</th>
                    </tr>
                </thead>

                    <% @tracked_stocks.each do |stock| %>
                        <tbody>
                            <tr>
                            <th scope="row"><%= stock.ticker %></th>
                            <td><%= stock.name %></td>
                            <td><%= stock.last_price %></td>
                            <td><% if current_user.can_track_stock?(stock.ticker) %>
                                    <%= link_to "Add to Portfolio", user_stocks_path(user: current_user, ticker:stock.ticker),class: "btn btn-xs btn-success",method: :post %>
                                <% elsif current_user.id != @user.id %>
                                    <span class = "badge  text-bg-secondary">
                                    You already tracking
                                    <% if !current_user.under_stock_limit? %>
                                        10 stocks
                                    <% end %>
                                    <% if current_user.stock_already_tracked?(stock.ticker) %>
                                            this stock
                                    <% end %>
                                    </span>
                                <% end %>
                            <% if current_user.id == @user.id %>
                                <%= button_to  "Remove",user_stock_path(stock), method: :delete,data: {"turbo_confirm": "Are you sure"},class: "btn btn-sm btn-warning" %>
                                <% end %>
                            </td>
                            </tr>
                        </tbody>
                    <% end %>

            </table>

        </div>
    </div>

app/views/users/_friend_result.html.erb
<%= (render partial: 'layouts/messages') %>
<div class = "display">
    <% if @friends %>

        <div class = "card card-header results-block">
            <table class="table table-dark table-borderless table-hover">
                <thead>
                    <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Profile</th>
                    <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                <% @friends.each do |friend| %>
                    <tr>
                    <td><%= friend.full_name %></td>
                    <td><%= friend.email %></td>
                    <td><%= link_to "View Profile", user_path(friend), class: "btn btn-xs btn-success" %></td>
                    <% if current_user.not_friends_with?(friend.id) %>
                        <td><%= link_to "Follow friend?", friendships_path(friend: friend),class: "btn btn-xs btn-success",method: :post %></td>
                    <% else %>
                        <td>You are friends<td>
                    <% end %>
                    </tr>
                <% end %>
                </tbody>
            </table>
        </div>
    <% end %>
</div>

app/views/users/_friend_result.js.erb
document.querySelector('#friend_result').insertAdjacentHTML( "afterbegin","<%= escape_javascript(render partial:'users/friend_result',formats: :html )%>");
 search_result = document.querySelector(".display")
 submit_button = document.querySelector(".submit")

if (search_result){
    submit_button.addEventListener('click',function(e){
        search_result.innerHTML =""
    })
}

app/views/users/_result.html.erb
<%= (render partial: 'layouts/messages') %>
<div class = "display">
        <% if @stock %>
            <div class = "card card-header results-block">
                <strong>Symbol: </strong><%= @stock.ticker %>
                <strong>Name: </strong><%= @stock.name %>
                <strong>Price: </strong><%= @stock.last_price %>
                <% if current_user.can_track_stock?(@stock.ticker) %>
                    <%= link_to "Add to Portfolio", user_stocks_path(user: current_user, ticker:@stock.ticker),class: "btn btn-xs btn-success",method: :post %>
                <% else %>
                    <span class = "badge  text-bg-secondary">
                    You already tracking
                    <% if !current_user.under_stock_limit? %>
                        10 stocks
                    <% end %>
                    <% if current_user.stock_already_tracked?(@stock.ticker) %>
                            this stock
                    <% end %>
                    </span>
                <% end %>
            </div>
        <% end %>
</div>

app/views/users/_result.js.erb
document.querySelector('#results').insertAdjacentHTML( "afterbegin","<%= escape_javascript(render partial:'users/result',formats: :html )%>");
 search_result = document.querySelector(".display")
 submit_button = document.querySelector(".submit")

if (search_result){
    submit_button.addEventListener('click',function(e){
        search_result.innerHTML =""
    })
}

app/views/users/my_friends.html.erb
<h1>Friends</h1>

<div class = "search-area">
    <h3>Search Friends</h3>
    <%= form_with  url: search_friend_path,method: :get,local: false do |f| %>
        <div class = 'form-group row'>
            <div class = "col-sm-9 no-right-padding">
                <%= f.text_field :friend ,placeholder: "Name or Email",autofocus: true, class: "form-control form-control-lg" %>
            </div>
            <div class = "col-sm-3 no-left-padding" >
               <%= f.button type: :submit, class: " submit btn btn-success" do %>
                    <%= fa_icon 'search 2x' %>
                <% end %>
            <div>
        </div>
    <% end %>

</div>

<div id = "friend_result">
</div>

<% if !@friends.empty? %>
    <%= render 'friends/list' %>

<% end %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>
<div class = "search-area">
    <h3>Search Stocks</h3>
    <%= form_with  url: search_stock_path,method: :get,local: false do |f| %>
        <div class = 'form-group row'>
            <div class = "col-sm-9 no-right-padding">
                <%= f.text_field :stock ,placeholder: "Stock ticker symbol",autofocus: true, class: "form-control form-control-lg" %>
            </div>
            <div class = "col-sm-3 no-left-padding" >
               <%= f.button type: :submit, class: " submit btn btn-success" do %>
                    <%= fa_icon 'search 2x' %>
                <% end %>
            <div>
        </div>
    <% end %>

</div>
<div id = "results">


<div>
<div id  = "table">
    <% if  !@tracked_stocks.empty?%>
    <%= render partial: "stocks/list"%>
    <% end %>
</div>


 

app/views/users/show.html.erb
<h2>User Details</h2>

<div class = "display">

        <div class = "card card-header results-block">
            <table class="table table-dark table-borderless table-hover">
                <thead>
                    <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Profile</th>
                    <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>

                    <tr>
                    <td><%= @user.full_name %></td>
                    <td><%= @user.email %></td>
                    <td></td>
                    <% if current_user.not_friends_with?(@user.id) %>
                        <td><%= link_to "Follow friend?", friendships_path(friend: @user),class: "btn btn-xs btn-success",method: :post %></td>
                    <% else %>
                        <td>You are friends<td>
                    <% end %>
                    </tr>

                </tbody>
            </table>
        </div>
</div>

<% if  !@tracked_stocks.empty? %>
    <%= render partial: "stocks/list" %>
<% else %>
    <p class = "lead">This user is not tracking any stocks</p>
<% end %>

app/views/welcome/index.html.erb
<h1> Welcome to the Finance Tracker app </h1>

<p>Create a welcome page</p>